title: Pranav Chaturvedi
email: pranavchat14@gmail.com
author: Pranav Chaturvedi
description: >- # this means to ignore newlines until "baseurl:"
  About all things Artificial Intelligence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pranavchat.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pranavchatman
github_username:  pranavchat14

theme: minima

permalink: /:categories/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->


plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-twitter-plugin


kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
  sass_dir: _sass


google_analytics: G-RVWRJ2KKZZ

disqus:
  shortname: pranavchat

